name: ample-gcg
suffix_length: 20
topk: 256
search_width: 64
num_groups: 4
group_beam_size: 4
diversity_penalty: 0.5
diversity_type: ngram
ngram_size: 2
temperature: 0.7
do_sample: True
top_p: 0.95
save_dir: results/ample_gcg
llm_save_name: attack_train
train_cfg_path: configs/train/ample-gcg/cfg-1.yaml
lora_cfg_path: configs/train/lora.yaml
dataset: harmbench
target_llm: null
prompter_model_id: null
auto_train: true
random_seed: 42
