name: adv-prompter
suffix_length: 20
epoch: 10
search_width: 64
batch_size: 4
width_bs: -1
disable_tqdm: false
num_beams: 4
num_chunks: 1
repetition_penalty: 1.2
topk: 48
lambda_val: 100
candidates:
  do_sample: true
  temperature: 0.6
  always_include_best: true
beams:
  do_sample: true
  temperature: 0.6
  always_include_best: true
train:
  epochs: 10
  do_initial_eval: false
  eval_every: 1
  augment_target: true
  replay_buffer:
    num_updates: 8
    size: 5000
    priority_alpha: 0.6
    priority_factor:
      loss_delta: 1.0
      jailbreaking: 1.0
  prompter_optim_params:
    lr: 0.005
save_dir: results/adv_prompter
save_name: adv_prompter_cfg2
lora_cfg_path: configs/train/lora.yaml
prompter_model_id: null
target_llm: null
dataset: advbench
auto_train: true
random_seed: 123
